scoredict = {
     0: ["   ",
         "XXX",
         "X X",
         "X X",
         "X X",
         "XXX",
         "   "],
    1: ["   ",
        " X ",
        "XX ",
        " X ",
        " X ",
        "XXX",
        "   "],
    2: ["   ",
        "XXX",
        "  X",
        "XXX",
        "X  ",
        "XXX",
        "   "],
      3: ["   ",
          "XXX",
          "  X",
          "XXX",
          "  X",
          "XXX",
          "   "],
     4: ["   ",
         "X X",
         "X X",
         "XXX",
         "  X",
         "  X",
         "   "],
      5: ["   ",
          "XXX",
          "X  ",
          "XXX",
          "  X",
          "XXX",
          "   "],
      6: ["   ",
          "XXX",
          "X  ",
          "XXX",
          "X X",
          "XXX",
          "   "],
    7: ["   ",
          "XXX",
          "  X",
          "  X",
          "  X",
          "  X",
          "   "],
    8: ["   ",
          "XXX",
          "X X",
          "XXX",
          "X X",
          "XXX",
          "   "],
    9: ["   ",
          "XXX",
          "X X",
          "XXX",
          "  X",
          "  X",
          "   "],
}

textdict={
    "A": ["   ",
         "XXX",
         "X X",
         "XXX",
         "X X",
         "X X",
         "   "],
    "B": ["   ",
         "XXX",
         "X X",
         "XXX",
         "X X",
         "XXX",
         "   "],
    "C": ["   ",
         "XXX",
         "X  ",
         "X  ",
         "X  ",
         "XXX",
         "   "],
    "D": ["   ",
         "XX ",
         "X X",
         "X X",
         "X X",
         "XX ",
         "   "],
    "E": ["   ",
         "XXX",
         "X  ",
         "XXX",
         "X  ",
         "XXX",
         "   "],
    "F": ["   ",
         "XXX",
         "X  ",
         "XXX",
         "X  ",
         "X  ",
         "   "],
    "G": ["   ",
         "XXX",
         "X  ",
         "X X",
         "X X",
         "XXX",
         "   "],
    "H": ["   ",
         "X X",
         "X X",
         "XXX",
         "X X",
         "X X",
         "   "],
    "I": ["   ",
         "XXX",
         " X ",
         " X ",
         " X ",
         "XXX",
         "   "],
    "J": ["   ",
         "XXX",
         "  X",
         "  X",
         "  X",
         "XX ",
         "   "],
    "K": ["   ",
         "X X",
         "X X",
         "XX ",
         "X X",
         "X X",
         "   "],
    "L": ["   ",
         "X  ",
         "X  ",
         "X  ",
         "X  ",
         "XXX",
         "   "],
    "M": ["     ",
         "X   X",
         "XX XX",
         "X X X",
         "X   X",
         "X   X",
         "     "],
    "N": ["    ",
         "X  X",
         "XX X",
         "X XX",
         "X  X",
         "X  X",
         "    "],
    "O": ["   ",
         "XXX",
         "X X",
         "X X",
         "X X",
         "XXX",
         "   "],
    "P": ["   ",
         "XXX",
         "X X",
         "XXX",
         "X  ",
         "X  ",
         "   "],
    "Q": ["     ",
         "XXXX ",
         "X  X ",
         "X  X ",
         "X XX ",
         "XXX X",
         "     "],
    "R": ["   ",
         "XXX",
         "X X",
         "XXX",
         "XX ",
         "X X",
         "   "],
    "S": ["   ",
         "XXX",
         "X  ",
         "XXX",
         "  X",
         "XXX",
         "   "],
    "T": ["   ",
         "XXX",
         " X ",
         " X ",
         " X ",
         " X ",
         "   "],
    "U": ["   ",
         "X X",
         "X X",
         "X X",
         "X X",
         "XXX",
         "   "],
    "V": ["   ",
         "X X",
         "X X",
         "X X",
         "X X",
         " X ",
         "   "],
    "W":["     ",
         "X   X",
         "X   X",
         "X   X",
         "X X X",
         "XXXXX",
         "     "],
    "X":["    ",
         "X X",
         "X X ",
         " X  ",
         "X X ",
         "X X",
         "   "],
    "Y":["    ",
         "X X",
         "X X",
         "X X ",
         " X  ",
         " X  ",
         "    "],
    "Z":["     ",
         "XXXX",
         "   X",
         "  X ",
         " X  ",
         "XXXX",
         "    "],
    "!": ["  ",
            "X ",
            "X ",
            "X ",
            "  ",
            "X ",
            "  "],
    "-": ["    ",
          "    ",
          "    ",
          " XX ",
          "    ",
          "    ",
          "    "]
}

scoredict["dash"] = textdict["-"]
scoredict = {
     0: ["   ",
         "XXX",
         "X X",
         "X X",
         "X X",
         "XXX",
         "   "],
    1: ["   ",
        " X ",
        "XX ",
        " X ",
        " X ",
        "XXX",
        "   "],
    2: ["   ",
        "XXX",
        "  X",
        "XXX",
        "X  ",
        "XXX",
        "   "],
      3: ["   ",
          "XXX",
          "  X",
          "XXX",
          "  X",
          "XXX",
          "   "],
     4: ["   ",
         "X X",
         "X X",
         "XXX",
         "  X",
         "  X",
         "   "],
      5: ["   ",
          "XXX",
          "X  ",
          "XXX",
          "  X",
          "XXX",
          "   "],
      6: ["   ",
          "XXX",
          "X  ",
          "XXX",
          "X X",
          "XXX",
          "   "],
    7: ["   ",
          "XXX",
          "  X",
          "  X",
          "  X",
          "  X",
          "   "],
    8: ["   ",
          "XXX",
          "X X",
          "XXX",
          "X X",
          "XXX",
          "   "],
    9: ["   ",
          "XXX",
          "X X",
          "XXX",
          "  X",
          "  X",
          "   "],
}

textdict={
    "A": ["   ",
         "XXX",
         "X X",
         "XXX",
         "X X",
         "X X",
         "   "],
    "B": ["   ",
         "XXX",
         "X X",
         "XXX",
         "X X",
         "XXX",
         "   "],
    "C": ["   ",
         "XXX",
         "X  ",
         "X  ",
         "X  ",
         "XXX",
         "   "],
    "D": ["   ",
         "XX ",
         "X X",
         "X X",
         "X X",
         "XX ",
         "   "],
    "E": ["   ",
         "XXX",
         "X  ",
         "XXX",
         "X  ",
         "XXX",
         "   "],
    "F": ["   ",
         "XXX",
         "X  ",
         "XXX",
         "X  ",
         "X  ",
         "   "],
    "G": ["   ",
         "XXX",
         "X  ",
         "X X",
         "X X",
         "XXX",
         "   "],
    "H": ["   ",
         "X X",
         "X X",
         "XXX",
         "X X",
         "X X",
         "   "],
    "I": ["   ",
         "XXX",
         " X ",
         " X ",
         " X ",
         "XXX",
         "   "],
    "J": ["   ",
         "XXX",
         "  X",
         "  X",
         "  X",
         "XX ",
         "   "],
    "K": ["   ",
         "X X",
         "X X",
         "XX ",
         "X X",
         "X X",
         "   "],
    "L": ["   ",
         "X  ",
         "X  ",
         "X  ",
         "X  ",
         "XXX",
         "   "],
    "M": ["     ",
         "X   X",
         "XX XX",
         "X X X",
         "X   X",
         "X   X",
         "     "],
    "N": ["    ",
         "X  X",
         "XX X",
         "X XX",
         "X  X",
         "X  X",
         "    "],
    "O": ["   ",
         "XXX",
         "X X",
         "X X",
         "X X",
         "XXX",
         "   "],
    "P": ["   ",
         "XXX",
         "X X",
         "XXX",
         "X  ",
         "X  ",
         "   "],
    "Q": ["     ",
         "XXXX ",
         "X  X ",
         "X  X ",
         "X XX ",
         "XXX X",
         "     "],
    "R": ["   ",
         "XXX",
         "X X",
         "XXX",
         "XX ",
         "X X",
         "   "],
    "S": ["   ",
         "XXX",
         "X  ",
         "XXX",
         "  X",
         "XXX",
         "   "],
    "T": ["   ",
         "XXX",
         " X ",
         " X ",
         " X ",
         " X ",
         "   "],
    "U": ["   ",
         "X X",
         "X X",
         "X X",
         "X X",
         "XXX",
         "   "],
    "V": ["   ",
         "X X",
         "X X",
         "X X",
         "X X",
         " X ",
         "   "],
    "W":["     ",
         "X   X",
         "X   X",
         "X   X",
         "X X X",
         "XXXXX",
         "     "],
    "X":["    ",
         "X X",
         "X X ",
         " X  ",
         "X X ",
         "X X",
         "   "],
    "Y":["    ",
         "X X",
         "X X",
         "X X ",
         " X  ",
         " X  ",
         "    "],
    "Z":["     ",
         "XXXX",
         "   X",
         "  X ",
         " X  ",
         "XXXX",
         "    "],
    "!": ["  ",
            "X ",
            "X ",
            "X ",
            "  ",
            "X ",
            "  "],
    "-": ["    ",
          "    ",
          "    ",
          " XX ",
          "    ",
          "    ",
          "    "]
}

scoredict["dash"] = textdict["-"]
